name: CI

on:
  push:
  pull_request:

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }}) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        php:
          - 7.4
#          - 8.0
#          - 8.1
#          - 8.2
#          - 8.3
#          - 8.4
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
      - name: Pull AutoBahn Docker Image
        run: docker pull crossbario/autobahn-testsuite
      - name: Start Autobahn TestSuite Server
        run: docker run -d --name fuzzingserver --rm -it -v tests/autobahn:/config -v tests/autobahn/reports:/reports --name fuzzingclient -p 9001:9001 crossbario/autobahn-testsuite wstest -m fuzzingserver -s /config/fuzzingserver.json
      - name: Wait for Autobahn TestSuite Server to start
        run: |
          for i in {1..30}; do
            if nc -z localhost 9001; then
              echo "Server is up!";
              exit 0;
            fi
            echo "Waiting for server..."
            sleep 2
          done
          echo "Server failed to start"
          exit 1
      - name: Install Composer Dependencies
        run: composer install
      - name: Run Autobahn TestSuite
        run: php tests/autobahn/runner.php
      - run: vendor/bin/phpunit --coverage-text

